language: csharp
solution: './src/System.Windows.Forms.Ribbon.sln'
script:
- xbuild ./src/System.Windows.Forms.Ribbon.sln
deploy:
  provider: releases
  api_key: "1FCi1GtBrMlL6OmC8NArLA"
  file: "RibbonWinFormsRelease"
  skip_cleanup: true
  on:
    tags: true
